# This workflow will build a .NET project Heemi
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test with coverage
      run: dotnet test --no-build --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=./coverage/
    - name: Publish coverage report
      uses: actions/upload-artifact@v3
      with:
          name: cobertura-coverage-report
          path: ./coverage/coverage.cobertura.xml
    - name: Publish code coverage results
      uses: github/codeql-action/upload-sarif@v2
      with:
          sarif_file: ./coverage/coverage.cobertura.xml
